#!/bin/bash

SUBCHAR=!
CMDNO=1

[[ "$*" =~ $SUBCHAR ]] && WORK=$* || WORK="$* $SUBCHAR"

echo -n "[botchcli ${CMDNO}] $WORK> "
while read LINE; do
  if [ "x$LINE" == "x" ] ; then
    echo -n
  elif [ "x${LINE,,}" == "xquit" ] ; then
    exit 0
  else
    ${WORK/$SUBCHAR/$LINE}
  fi
  CMDNO=$((${CMDNO} + 1))
  echo -n "[botchcli ${CMDNO}] $WORK> "
done
